#!/usr/bin/env sh
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/Basement"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/BasementGHT.idd"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/convertESOMTR"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/EnergyPlus"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/Energy+.idd"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/Energy+.schema.epJSON"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/EP-Compare"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/EPMacro"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/ExpandObjects"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/HVAC-Diagram"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/IDFVersionUpdater"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/ParametricPreprocessor"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/parser"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/ReadVarsESO"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/runenergyplus"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/runepmacro"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/runreadvars"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/Slab"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/SlabGHT.idd"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/Transition-V8-2-0-to-V8-3-0"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/V8-2-0-Energy+.idd"
      rm -f "/home/ict4bd_v2/Desktop/building/energyplus/V8-3-0-Energy+.idd"
      rm -f /usr/local/share/man/man1/energyplus.1
echo "Symbolic links to this installation of EnergyPlus have been removed."
echo "You may remove the EnergyPlus directory to completely uninstall the software."
